pub mod Errors {
    pub const USERNAME_TAKEN: felt252 = 'USERNAME_TAKEN';
    pub const INVALID_USERNAME: felt252 = 'INVALID_USERNAME';
    pub const INVALID_ADDRESS: felt252 = 'INVALID_ADDRESS';
    pub const CALLER_ALREADY_HAVE_USERNAME: felt252 = 'CALLER_ALREADY_HAVE_USERNAME';
    pub const INVALID_CHAIN_SYMBOL: felt252 = 'INVALID_CHAIN_SYMBOL';
    pub const INVALID_WALLET_ADDRESS: felt252 = 'INVALID_WALLET_ADDRESS';
    pub const USER_NOT_REGISTERED: felt252 = 'USER_NOT_REGISTERED';
    pub const WALLET_NOT_FOUND: felt252 = 'WALLET_NOT_FOUND';
    pub const chain_symbol_NOT_FOUND: felt252 = 'chain_symbol_NOT_FOUND';
    pub const ADDRESS_ALREADY_HAS_USERNAME: felt252 = 'ADDRESS_ALREADY_HAS_USERNAME';
    pub const ACCOUNT_ALREADY_INACTIVE: felt252 = 'ACCOUNT_ALREADY_INACTIVE';
    pub const ACCOUNT_ALREADY_ACTIVE: felt252 = 'ACCOUNT_ALREADY_ACTIVE';
    pub const ACCOUNT_INACTIVE: felt252 = 'ACCOUNT_INACTIVE';
}
