pub mod Errors {
    pub const USERNAME_TAKEN: felt252 = 'USERNAME_TAKEN';
    pub const INVALID_USERNAME: felt252 = 'INVALID_USERNAME';
    pub const INVALID_ADDRESS: felt252 = 'INVALID_ADDRESS';
    pub const CALLER_ALREADY_HAVE_USERNAME: felt252 = 'CALLER_ALREADY_HAVE_USERNAME';
    pub const INVALID_CHAIN_ID: felt252 = 'INVALID_CHAIN_ID';
    pub const INVALID_WALLET_ADDRESS: felt252 = 'INVALID_WALLET_ADDRESS';
    pub const USER_NOT_REGISTERED: felt252 = 'USER_NOT_REGISTERED';
}
