name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gateway
    steps:
      - uses: actions/checkout@v3

      - name: Setup Cairo environment
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.11.2

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: 0.48.1

      - name: Check Cairo format
        run: scarb fmt --check

      - name: Build Cairo programs
        run: scarb build

      - name: Run Cairo tests
        run: snforge test
