name: Contracts CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install asdf
        uses: asdf-vm/actions/setup@v2

      - name: Install plugins
        run: |
          asdf plugin add scarb
          asdf install scarb 2.10.1
          asdf global scarb 2.10.1
          asdf plugin add dojo https://github.com/dojoengine/asdf-dojo
          asdf install dojo 1.5.0 
          asdf global dojo 1.5.0
          asdf plugin add starknet-foundry
          asdf install starknet-foundry 0.35.0
          asdf global starknet-foundry 0.35.0

      - name: Build contracts
        run: |
          cd src
          sozo build

      - name: Run tests
        run: |
          cd src
          sozo test

      - name: Check formatting
        run: |
          cd src
          scarb fmt --check

      # - name: ERC721
      #   run: |
      #     cd 
      #     scarb build
      #     snforge test
      #     scarb fmt --check