name: Contracts CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.1"

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v4
        with:
          starknet-foundry-version: "0.48.1"

      - name: Build contracts
        working-directory: gateway
        run: scarb build

      - name: Run tests
        working-directory: gateway
        run: scarb test

      - name: Check formatting
        working-directory: gateway
        run: scarb fmt --check
